version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: byteforge_db
    environment:
      POSTGRES_USER: byteforge
      POSTGRES_PASSWORD: root
      POSTGRES_DB: byteforge_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: