# Базовые настройки приложения
spring.application.name=${SPRING_APP_NAME:ByteForgeOnlineStore}

# Активный профиль
spring.profiles.active=prod

# Импорт настроек прод профиля
spring.config.import=application_prod.properties
