-- Categories
INSERT INTO categories (name, slug) VALUES 
('Graphics cards', 'gpu'),
('Central processing unit',	'cpu'),
('Motherboard',	'mother'),
('Random access memory', 'ram'),
('Power supply unit', 'psu'),
('PC cases', 'case'),
('Monitors', 'moni'),
('Solid state drive', 'ssd'),
('Mice', 'mice'),
('Computer keyboard', 'keybrd'); 

-- Brands
INSERT INTO brands (name, logo_url) VALUES
-- Производители GPU
('NVIDIA', '/logo/nvidia.png'),
('AMD', '/logo/amd.png'),
('ASUS', '/logo/asus.png'),
('MSI', '/logo/msi.png'),
('Gigabyte', '/logo/gigabyte.png'),
('ASRock', '/logo/asrock.png'),
('ZOTAC', '/logo/zotac.png'),
('PowerColor', '/logo/powercolor.png'),
('Sapphire', '/logo/sapphire.png'),
('XFX', '/logo/xfx.png'),
('Intel', '/logo/intel.png'),
('PNY', '/logo/pny.png'),
('EVGA', '/logo/evga.png'),
('Inno3D', '/logo/inno3d.png'),
('Palit', '/logo/palit.png'),

-- Производители RAM
('Supermicro','/logo/supermicro.png'),
('G.Skill', '/logo/gskill.png'),
('Corsair', '/logo/corsair.png'),
('Kingston', '/logo/kingston.png'),
('Crucial', '/logo/crucial.png'),
('TeamGroup', '/logo/teamgroup.png'),
('ADATA', '/logo/adata.png'),
('Patriot', '/logo/patriot.png'),
('Silicon Power', '/logo/siliconpower.png'),
('GeIL', '/logo/geil.png'),
('OLOy', '/logo/oloy.png'),
('Apacer', '/logo/apacer.png'),
('Klevv', '/logo/klevv.png'),
('Goodram', '/logo/goodram.png'),

-- Производители блоков питания
('Seasonic', '/logo/seasonic.png'),
('be quiet!', '/logo/bequiet.png'),
('Super Flower', '/logo/superflower.png'),
('Cooler Master', '/logo/coolermaster.png'),
('Thermaltake', '/logo/thermaltake.png'),
('FSP', '/logo/fsp.png'),
('NZXT', '/logo/nzxt.png'),
('Deepcool', '/logo/deepcool.png'),
('Lian Li', '/logo/lianli.png'),
('SilverStone', '/logo/silverstone.png'),

-- Производители корпусов 
('Fractal Design', '/logo/fractaldesign.png'),
('Phanteks', '/logo/phanteks.png'),
('Antec', '/logo/antec.png'),
('HYTE', '/logo/hyte.png'),
('InWin', '/logo/inwin.png'),
('Singularity Computers', '/logo/singularitycomputers.png'),
('AZZA', '/logo/azza.png'),
('MONTECH', '/logo/montech.png'),
('SSUPD', '/logo/ssupd.png'),
('Jonsbo', '/logo/jonsbo.png'),
('MetalFish', '/logo/metalfish.png'),
('DarkFlash', '/logo/darkflash.png'),
('Zalman', '/logo/zalman.png'),
('Xigmatek', '/logo/xigmatek.png'),
('Raijintek', '/logo/raijintek.png'),
('Apevia', '/logo/apevia.png'),
('KEDIERS', '/logo/kediers.png'),
('CyberPowerPC', '/logo/cyberpowerpc.png'),
('Cougar', '/logo/cougar.png'),

-- Добавляем недостающие бренды мониторов
('LG', '/logo/lg.png'),
('Samsung', '/logo/samsung.png'),
('Alienware', '/logo/alienware.png'),
('Acer', '/logo/acer.png'),
('ViewSonic', '/logo/viewsonic.png'),
('BenQ', '/logo/benq.png'),
('Dell', '/logo/dell.png'),
('HP', '/logo/hp.png'),
('Apple', '/logo/apple.png'),
('EIZO', '/logo/eizo.png'),
('NEC', '/logo/nec.png'),
('BOE', '/logo/boe.png'),
('Xiaomi', '/logo/xiaomi.png'),
('AOC', '/logo/aoc.png'),
('Lenovo', '/logo/lenovo.png'),
('Philips', '/logo/philips.png'),

-- Дополнительные производители SSD/жестких дисков
('Seagate', '/logo/seagate.png'),
('Toshiba', '/logo/toshiba.png'),
('Western Digital', '/logo/westerndigital.png'),
('SanDisk', '/logo/sandisk.png'),
('SK hynix', '/logo/skhynix.png'),
('Kioxia', '/logo/kioxia.png'),
('Lexar', '/logo/lexar.png'),
('Transcend', '/logo/transcend.png'),
('OCZ', '/logo/ocz.png'),
('Plextor', '/logo/plextor.png'), 

-- Дополнительные производители мышек 
('Razer', '/logo/razer.png'),
('Logitech', '/logo/logitech.png'),
('SteelSeries', '/logo/steelseries.png'),
('HyperX', '/logo/hyperx.png'),
('Glorious', '/logo/glorious.png'),
('Keychron', '/logo/keychron.png'),
('Redragon', '/logo/redragon.png'),
('Delux', '/logo/delux.png'),
('Kensington', '/logo/kensington.png'),
('Elecom', '/logo/elecom.png'),
('Perixx', '/logo/perixx.png'),
('Endgame Gear', '/logo/endgamegear.png'),
('Roccat', '/logo/roccat.png'),
('Trust', '/logo/trust.png'),
('A4Tech', '/logo/a4tech.png'),
('Bloody', '/logo/bloody.png'),
('Zowie', '/logo/zowie.png'),

-- Дополнительные производители клавиатур
('Royal Kludge', '/logo/royalkludge.png'),  
('NuPhy', '/logo/nuphy.png'),               
('Epomaker', '/logo/epomaker.png'),        
('Akko', '/logo/akko.png'),                
('Varmilo', '/logo/varmilo.png'),           
('IQUNIX', '/logo/iqunix.png'),             
('Ducky', '/logo/ducky.png'),               
('Anne Pro', '/logo/annepro.png'),          
('Filco', '/logo/filco.png');

